if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
"set ai			" always set autoindenting on
"set backup		" keep a backup file
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup redhat
  autocmd!
  " In text files, always limit the width of text to 78 characters
  autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
"csprg用于指定cscope的程序
   set csprg=/usr/bin/cscope
"csto=0,cscope 数据库先被搜索，搜索失败的情况下再搜索标签文件
   set csto=0
"cst,总同时搜索 cscope 数据库和标签文件
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin indent on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"

"设置cscope查询快捷键，以全屏新窗口形式打开
nmap \s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap \g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap \c :cs find c <C-R>=expand("<cword>")<CR><CR>
nmap \t :cs find t <C-R>=expand("<cword>")<CR><CR>
nmap \e :cs find e <C-R>=expand("<cword>")<CR><CR>
nmap \f :cs find f <C-R>=expand("<cfile>")<CR><CR>
nmap \i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap \d :cs find d <C-R>=expand("<cword>")<CR><CR>


"设置cscope查询快捷键，以水平新窗口形式打开
nmap \hs :scs find s <C-R>=expand("<cword>")<CR><CR>
nmap \hg :scs find g <C-R>=expand("<cword>")<CR><CR>
nmap \hc :scs find c <C-R>=expand("<cword>")<CR><CR>
nmap \ht :scs find t <C-R>=expand("<cword>")<CR><CR>
nmap \he :scs find e <C-R>=expand("<cword>")<CR><CR>
nmap \hf :scs find f <C-R>=expand("<cfile>")<CR><CR>
nmap \hi :scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap \hd :scs find d <C-R>=expand("<cword>")<CR><CR>



"设置cscope查询快捷键，以垂直新窗口形式打开
nmap \vs :vert scs find s <C-R>=expand("<cword>")<CR><CR>
nmap \vg :vert scs find g <C-R>=expand("<cword>")<CR><CR>
nmap \vc :vert scs find c <C-R>=expand("<cword>")<CR><CR>
nmap \vt :vert scs find t <C-R>=expand("<cword>")<CR><CR>
nmap \ve :vert scs find e <C-R>=expand("<cword>")<CR><CR>
nmap \vi :vert scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap \vd :vert scs find d <C-R>=expand("<cword>")<CR><CR>




